#! /bin/sh

bspc monitor -d 1 2 3 4 5
#bspc monitor eDP1 -n 0 -d 1 2 3 4 5
#bspc monitor DP1 -n 1 -d 1 2 3 4 5

bspc config border_width         10
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config honor_size_hints     false

#bspc rule -a Chromium desktop='^1'
bspc rule -a Pavucontrol state="floating"
bspc rule -a Gimp state="floating"
# emacs is fucky if it starts off tiled
bspc rule -a Emacs state="floating"

# start polybar
polybar bar1 &

# start applications
dropbox start &
nm-applet &
dunst &
redshift &
