#! /bin/sh

bspc monitor eDP1 -d I II III 
bspc monitor DP1 -d IV V VI

bspc config border_width         10
bspc config window_gap           20

bspc config split_ratio          0.60
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config honor_size_hints     false

#bspc rule -a Chromium desktop='^1'
bspc rule -a Pavucontrol state="floating"
bspc rule -a Gimp state="floating"
# emacs is fucky if it starts off tiled
bspc rule -a Emacs state="floating"

# start polybar
polybar bar1 &

# start applications
dropbox start &
nm-applet &
dunst &
